// src/core/common/theme.js
export const COLORS = {
    mainSourceColor: "#769CDF",
    primary: "#415F91",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D6E3FF",
    onPrimaryContainer: "#284777",
    secondary: "#565F71",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#DAE2F9",
    onSecondaryContainer: "#3E4759",
    tertiary: "#705575",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FAD8FD",
    onTertiaryContainer: "#573E5C",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    surfaceDim: "#D9D9E0",
    surface: "#F9F9FF",
    surfaceBright: "#F9F9FF",
    onSurface: "#191C20",
    onSurfaceVariant: "#44474E",
    outline: "#74777F",
    outlineVariant: "#C4C6D0",
    neutral: "#919093",
    neutralVariant: "#8E9098",
};

export const FONTS = {
    italic: "Roboto-Italic",
    light: "Roboto-Light",
    regular: "Roboto-Regular",
    semiBold: "Roboto-SemiBold",
    bold: "Roboto-Bold",
};
